[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#1B1B1B"
blue = "#79A9FF"
cyan = "#9aedfe"
green = "#50fa7b"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.normal]
black = "#1B1B1B"
blue = "#6790EB"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#000000"
foreground = "#F9F9F9"

[font]
size = 11.6

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[scrolling]
history = 50000

[window]
opacity = 1
